version: '3.4'

networks:
  gringottsnetwork:
    driver: bridge

services:
  gringottsbank.api:
    image: ${DOCKER_REGISTRY-}gringottsbankapi
    build:
      context: .
      dockerfile: Dockerfile

  gringottsdb:
    image: postgres:latest

volumes:
  db_volume: